### ISSUE TITLE
fixture itemName/collection name must be same?

### ISSUE THREAD

**Issue by ghost** [mgan59/mongoose-fixture#11]
in basefixtureloader
        var fixtureModel = mongoose.model(fixtureItem, fixtureSchema);
so looks like model name is the fixture.itemName.

in mongoosefixture
                        if(name === item.collection){
                            collectionExists = true;
                        }
for deletes

adding seems to use fixture.itemName and remove seems to use the fixture.collection. If I set these two the same, everything works fine. If they are different, the remove code breaks.

**Comment by mgan59** [comment]
@roger-kaybus k will look into it.  I remember thinking at one point that the interface seemed redundant, but there was a reason I made the decision and I think it has to do with the way mongoose works.  I'll look into it and let you know.

**Comment by mgan59** [comment]
Reviewed some of the code fairly quickly.  I think my intention was as follows.  

A little background on Mongoosejs, by default it will take whatever 'ModelKey' you pass into `Mongoose.model('ModelKey', Schema)` and if you do not specify a collection name in the [schema.options.collection](http://mongoosejs.com/docs/guide.html#collection) it will attempt to generate one for you.  For instance if you did `Mongoose.model('Kitten', Schema)` it would create a collection in mongodb called `kittens`.

There are problems with Mongoosejs auto-generating collection names, specifically I had an instance of the model 'Facility' which was generating `facilitys` which is inaccurate I wanted `facilities` so in my schema I set the collection option to facilities.  The problem then when I ran mongoose-fixture with just a `collection` key of 'facilities' the `Mongoose.model(...)` method was incapable of finding the correct model/collection mapping. Even though the delete would work since the collection name did map correctly.

So... with that said I reviewed my project that has multiple mis-matching itemName / collection names and they work fine... I think your problem might be in setting two different values you need to map your fixture.collection to the custom collection name you define on your scheme 

``` javascript

module.exports = function(mongoose){

    var facilitySchema = mongoose.Schema({
            internalName:{type:String},
            name:{type:String},
        },
        // extra options, this overrides the default collection name
        // that would be set by model as facilitys
        {
            collection:'facilities'   
        }
    );

    return facilitySchema;
};
```

Let me know if this solves your problem.  Maybe I'll see what my options are for warning a client that by mis-matching itemName and Collection requires the `collection` to be defined on the scheme.  Pretty sure I can bubble the message up.

**Comment by mgan59** [comment]
@roger-kaybus when you get a chance let me know the status and if you're all set please close the issue.

**Comment by ghost** [comment]
its working for me fine right now. I'll close this.
