### ISSUE TITLE
MissingSchemaError: Schema hasn't been registered for model "Product".

### ISSUE THREAD

**Issue by lvarayut** [mgan59/mongoose-fixture#25]
It seems that `Mongoose-fixture` is trying to access all the files in the `schema` folder. In my opinion, it isn't necessary to do that, it should look up only the schema defined in `mongoose-fixture-config.js`:

``` javascript
var allFixtures = [    
    {
        schema:'Product',
        data:'product',
        collection:'products'
    }  
];
```

So, in this case, it should look up only the `product.js` placed in `schema` folder. When it looked up all the schema files, it ran to `history.js` before `product.js`. This is the cause of the problem. 

``` javascript
// history.js
module.exports = function(mongoose, conn) {
    var ProductSchema = mongoose.model('Product').schema;
    var HistorySchema = new mongoose.Schema({
        ...
        products: {
            type: [ProductSchema]
        }
    });

    mongoose.model('History', HistorySchema);
    return {
        name: 'History',
        schema: HistorySchema
    };
};
```

This is my point of view, it may be wrong. Thanks in advance for your suggestion on how to solve it.

**Comment by mgan59** [comment]
The `schema` defined is what is used for deletion/reset and that is the purpose of that attribute.  The fixture config loads all the schemas so that they are accessible in the fixtures themselves without having to bind them to mongoose as that would be overly verbose and could lead to duplication which would throw an error.

Based on the code you posted I'm not entirely sure if you are structuring your fixtures/schemas correctly.  If you were to create a public repo with a more concrete example I could help identify if there is a valid issue or not.

Cheers.

**Comment by lvarayut** [comment]
Thanks for you help! I didn't have a lot of things in my fixtures/schemas.  The `History` schema has been structured as show in the previous post. Here is my `Product Fixture` and my `Product schema`.

**Product Fixture:**

``` javascript
/*
 *  File: product.js
 *  Type: DataFixture
 *  Generated by: Mongoose-Fixture (v0.4.1)
 *
 */

module.exports = function(mongoose, conn, callback) {

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];

    /*
     * Example of adding a data document/fixture item
     */
    fixture.push({
        // by not defining an _id mongoose-fixture
        // will by default set a mongo ObjectID
        // defining one manually will override mongoDB
        name: "Play for Java: Covers Play 2",
        type: "Book",
        description: "Play for Java shows you how to build Java-based web applications using the Play 2 framework...",
        company: "Manning Publications",
        price: 30,
        imagePath: "/public/assets/images/play-for-java.png",
        rating: 4.5,
        category: "Computer",
        author: "Nicolas Leroux",
        publicationDate: "2014-03-31",
        numPage: 320
    });
    return callback(error, fixture);
};
```

**Product Schema:**

``` javascript
module.exports = function(mongoose, conn) {
    var ProductSchema = mongoose.Schema({
        name: {
            type: String
        },
        type: {
            type: String
        },
        description: {
            type: String
        },
        company: {
            type: String
        },
        price: {
            type: Number
        },
        imagePath: {
            type: String
        },
        imageName: {
            type: String
        },
        rating: {
            type: Number
        },
        comments: {
            type: Array
        },
        userId: {
            type: String
        },
        category: {
            type: String
        },
        author: {
            type: String
        },
        publicationDate: {
            type: Date
        },
        numPage: {
            type: Number
        }
    });

    mongoose.model('Product', ProductSchema);

    return {
        name: 'Product',
        schema: ProductSchema
    };
};

```

**Comment by mgan59** [comment]
Sorry for the delay.  I had a chance to look at this code a little bit.  I think you need to adjust your mongoose schemas to use [populate](http://mongoosejs.com/docs/populate.html) so that you can properly [nest documents](http://stackoverflow.com/questions/14417150/mongoose-nested-documents).

Try:

``` javascript
// history.js
module.exports = function(mongoose, conn) {
    var Schema = mongoose.Schema;
    var HistorySchema = new mongoose.Schema({
        ...
        products: {
           type: Schema.Types.ObjectId, 
           ref: 'product', 
           required: true
        }
    });

    // I would recommend not registering your schemas here as it can create
    // a coupling issue when trying to share schemas/models with other services like express
    mongoose.model('History', HistorySchema);

    return {
        name: 'History',
        schema: HistorySchema
    };
};
```

If you make the schema adjustments everything should work :)  Let me know so I can close issue if it works.

**Comment by lvarayut** [comment]
It worked like a charm! :+1: As your recommendation, where should I register my schemas?

**Comment by mgan59** [comment]
I looked at some of my other projects/code and there are some that do it this way and they work perfectly fine.  So you are free to do this, but it could lead to a potential issue where an attempt to register a model twice can occur.  My suggestion would be during your apps initialization phase have it iterate over all the schemas/models in a directory and require each one and then using the returned `{name:'History', schema:HistorySchema}` have it register each one.  This is how I've done it in the past for express apps, that way all the models are registered already and I pass the `conn` object around.

By default if you are just running the example above from CLI then mongoose-fixture will automatically register your models during [init](https://github.com/mgan59/mongoose-fixture/blob/master/lib/MongooseFixture.js#L35).  So for your above example it should work without the `mongoose.model('History', HistorySchema);`

Recommend reading, mongoose-fixture uses `mongoose.createConnection` which is why I recommend using the `conn` object.  There is/was talk to deprecate the older [mongoose connection method](https://groups.google.com/forum/#!topic/mongoose-orm/30Dopgbsd98) which is best summed up on [StackOverflow](http://stackoverflow.com/questions/12806559/mongoose-model-vs-connection-model-vs-model-model).   As a note this is how mongoose-fixture can support multiple mongodb connections per #10

**Comment by mgan59** [comment]
Marking issue as closed as the main point was addressed :)

**Comment by lvarayut** [comment]
Thanks a lot for your help :)
